go-mysql: remove TestCache test, the operation result depends on the specific environment #701
[summary]
To resolve test result sometimes depends on the specific environment
--- FAIL: TestCache (1.41s)
	Error Trace:	caching_sha2_cache_test.go:160
			asm_amd64.s:1333
	Error:		Should be true

	Error Trace:	caching_sha2_cache_test.go:160
			asm_amd64.s:1333
	Error:		Should be true

[test case]
go-mysql/server/caching_sha2_cache_test.go

[patch codecov]
N/A